"""TASK B5 -- real vintage preseason projections, from the FFA Insider export.

WHAT CHANGED FROM B4. B4 asked whether audible's replacement transform earns its place and
had to ask it against a projection the harness built for itself, walking forward from prior
seasons. That projection was mediocre: within position the market's ADP ordering
correlated better with the outcome than that projection did in 9 of 16 position-seasons.
A null result on a weak input says very little about the transform.

These files are the market's own numbers as they stood before each draft, so the same
comparison now runs on a market-grade input. What is measured is still the ORDERING and never
the projection -- see the two standing limits at the bottom of this docstring.

THE FILES ARE GITIGNORED AND MUST STAY THAT WAY. This repository is public and the data is
derived from a paid FFA Insider subscription. `sim/data/ffa/README.md` and the `manifest.json`
`manifest()` writes are the only committed artefacts; the manifest records sha256 per file so a
run can assert it read the same bytes the artifact claims without the bytes being in git.

WHAT THE README GOT WRONG, measured rather than assumed (every claim below is re-derived by
`sim/test_g_b5.py` where a test can reach it):

  * `rec` IS ABSENT FROM SEVEN OF THE NINE SEASONS ON DISK, not two. The README says it is
    missing from
    2021 and 2023 and present in 2019, 2020, 2022, 2024 and 2025. Measured on the files on
    disk: the bare `rec` column exists in 2024 and 2025 ONLY. 2018, 2019, 2020, 2021, 2022,
    2023 and 2026 all carry `rec_yds` and `rec_tds` with no reception count. So the README's
    "PPR scoring 2019, 2020, 2022, 2024, 2025" is wrong; a PPR league can use 2024 and 2025.
  * IT DOES NOT BIND THIS RUN. League 6012 paid ZERO per reception in 2021-2025
    (`roundtrip.HISTORICAL_DELTAS`), so under the rulebook these seasons were actually played
    the reception weight is 0.0 and an absent reception count changes no score. That is a
    property of the LEAGUE, not of the data, which is exactly why `assert_scoreable` takes the
    EFFECTIVE weights and never a hardcoded season list.
  * DEFENCES STILL DO NOT SCORE. The README says kickers and defences "score for the first
    time". Half of that holds. FFA projects both, but a projection is only half a measurement:
    the OUTCOME comes from nflverse `player_stats`, which carries kicking columns
    (`fg_made_0_19` ... `pat_made`) and NO team-defence rows at all -- measured, position is
    never DST or DEF in any pinned season. So K can be scored on both sides and DEF cannot,
    and DEF is held at zero on BOTH sides rather than projected on one and scored on neither.
    A board that ranks defences it will never be paid for would spend real picks on them.

VINTAGE. Every season loaded is checked for the FOLLOWING year's draft class before it is
used (`assert_vintage`). A file regenerated by today's model would carry them; a genuine
vintage file cannot. This runs as a gate on every load and not merely once in a README.

2026 IS NOT AN ARM. The season has not happened, so there is no outcome to score it against.
`SCOREABLE` excludes it and `assert_scoreable_season` refuses it by name, because loading it
into an arm is a leak of a different kind: an unresolved season scored against nothing.

TWO LIMITS THAT STAY TRUE OF EVERY SIM RESULT, restated because this module is what makes the
stronger claim tempting. This measures ORDERING and never the projections -- the projections
here are FFA's, not audible's, and no vintage of audible's own consensus source exists. And
bots fitted to ADP are not people: they do not stack, reach for their own players, or panic.
"""

from __future__ import annotations

import csv
import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import room
from .adp_join import DEF_POSITIONS, normalize

FFA_DIR: Path = Path(__file__).resolve().parent / "data" / "ffa"

RAW_FILE = "raw_stats_{season}_wk0.csv"
PROJ_FILE = "projections_{season}_wk0.csv"

# The season has not been played. It is loadable for a cross-check against the live cockpit
# board and it is never an arm. G7.
UNPLAYED: frozenset[int] = frozenset({2026})

# Seasons the ROOM can replay, which is a tighter constraint than the projections are.
#
# A run season needs FOUR pinned inputs, not one: this projection, `player_stats_<S>` for the
# outcome, `ffc_adp_standard_8_<S>` for the market board every arm drafts off, and
# `espn_draft_6012_<S>` for the completed draft the opponent model is fitted from
# (`runner.required_inputs`). The projections reach back to 2018 and the other three do not:
# FFC ADP and the ESPN draft are pinned for 2021-2025 only.
#
# 2019 and 2020 are therefore UNRESOLVED rather than absent, and the distinction matters
# because the obvious diagnosis is wrong. `player_stats_2019` and `player_stats_2020` FETCH
# CLEANLY -- 17,362 and 17,602 rows, 32 teams, 256 regular-season games each -- and a prior
# session's note that 2020 was "absent from both cache roots" described the cache, not the
# upstream. What blocks those seasons is the MARKET side: no historical FFC board is pinned
# and this repository carries no fetcher for one, and the completed 6012 draft would need
# authenticated live ESPN access to a league whose draft is frozen. Neither is substitutable
# -- `room.resolve_input` refuses a nearby season by design -- so they are reported and not
# worked around.
SCOREABLE: tuple[int, ...] = (2021, 2022, 2023, 2024, 2025)

# FFA raw_stats column -> audible scoring-vocabulary key.
#
# ONE-WAY AND DELIBERATELY INCOMPLETE. Only keys FFA actually projects appear; a league weight
# with no column here is an UNSUPPLIED TERM and `assert_scoreable` decides what happens to it.
# Silence is the failure mode this map exists to prevent: `score_stat_line` resolves a missing
# key with `stats.get(key, 0.0)`, so an unmapped scoring term produces a plausible board and a
# wrong one.
COLUMN_TO_KEY: dict[str, str] = {
    "pass_yds": "pass_yd_raw",  # bucketed to 25s before it becomes `pass_yd`
    "pass_tds": "pass_td",
    "pass_int": "pass_int",
    "rush_yds": "rush_yd",
    "rush_tds": "rush_td",
    "rec": "rec",
    "rec_yds": "rec_yd",
    "rec_tds": "rec_td",
    "fumbles_lost": "fum_lost",
    "two_pts": "two_pts_any",
    "return_tds": "return_td_any",
    "fg_0019": "fgm_0_19",
    "fg_2029": "fgm_20_29",
    "fg_3039": "fgm_30_39",
    "fg_4049": "fgm_40_49",
    "fg_50": "fgm_50p",
    "xp": "xpm",
}

PASS_YARDS_RAW = "pass_yd_raw"
BUCKET = 25.0

# Keys the mapping DERIVES rather than reads. `pass_yds` arrives raw and leaves as `pass_yd`,
# bucketed to 25s, so the scoring key the league actually names is supplied whenever its source
# column is present. Kept explicit because `assert_scoreable` compares against scoring keys and
# would otherwise report the league's own `pass_yd` as an undeclared gap.
DERIVED_KEYS: dict[str, str] = {PASS_YARDS_RAW: "pass_yd"}

# FFA projects ONE two-point column and one return-touchdown column and does not say which
# phase they came from, while the league scores `pass_2pt`, `rush_2pt` and `rec_2pt`
# separately. Splitting one number three ways would be an invention, so both are carried under
# their own key and declared unsupplied for the league's keys. The largest projected `two_pts`
# in a season is about 5, so at the league's 2 points a conversion the term is worth up to ten
# points on one player -- small, but NOT nothing, and that is why it is declared rather than
# quietly mapped onto one of the three phase-specific keys.
SYNTHETIC_KEYS: frozenset[str] = frozenset({"two_pts_any", "return_td_any", PASS_YARDS_RAW})

# Scoring terms the FFA export carries no column for, per position, with the reason. A term in
# here scores ZERO and is recorded in the artifact; a non-zero-weighted term NOT in here raises.
# That is the whole of G3: every gap is either declared or fatal, and none is silent.
_TWO_PT = "FFA projects one undifferentiated `two_pts`; splitting it by phase is invention"
_NO_DST = "team D/ST is held at zero on both sides; nflverse carries no team-defence rows"

DECLARED_UNSUPPLIED: dict[str, str] = {
    "pass_2pt": _TWO_PT,
    "rush_2pt": _TWO_PT,
    "rec_2pt": _TWO_PT,
    "fum_rec_td": "no column; an offensive fumble recovered for a TD is not projected",
    "fgmiss": "FFA projects makes by bucket and never misses, so a miss cannot be priced",
    # Team D/ST. Declared rather than mapped because the OUTCOME side cannot score a defence
    # at all -- nflverse `player_stats` has no team-defence rows -- and a board that ranked
    # defences it will never be paid for would spend real picks on them.
    "sack": _NO_DST,
    "int": _NO_DST,
    "fum_rec": _NO_DST,
    "def_td": _NO_DST,
    "safe": _NO_DST,
    "blk_kick": _NO_DST,
    "pts_allow_0": _NO_DST,
    "pts_allow_1_6": _NO_DST,
    "pts_allow_7_13": _NO_DST,
    "pts_allow_14_20": _NO_DST,
    "pts_allow_28_34": _NO_DST,
    "pts_allow_35p": _NO_DST,
}

# Positions held at exactly zero on the projection side because the OUTCOME side cannot score
# them. See the module docstring. K is deliberately NOT in here: nflverse does carry kicking
# columns, so a kicker can be scored on both sides -- `sim/weekly.py` gates that separately.
ZERO_POSITIONS: frozenset[str] = frozenset({"DEF"})

# FFA position label -> audible position label.
POSITION_MAP: dict[str, str] = {"DST": "DEF", "PK": "K"}

# The following year's draft class, by the season file that must NOT contain them. G5.
# Names are checked normalised, so formatting differences between sources cannot fake a pass.
FOLLOWING_CLASS: dict[int, tuple[tuple[str, str], ...]] = {
    2018: (("Kyler Murray", "QB"), ("Josh Jacobs", "RB"), ("A.J. Brown", "WR")),
    2019: (("Joe Burrow", "QB"), ("Jonathan Taylor", "RB"), ("CeeDee Lamb", "WR")),
    2020: (("Trevor Lawrence", "QB"), ("Najee Harris", "RB"), ("Ja'Marr Chase", "WR")),
    2021: (("Kenny Pickett", "QB"), ("Breece Hall", "RB"), ("Garrett Wilson", "WR")),
    2022: (("C.J. Stroud", "QB"), ("Bijan Robinson", "RB"), ("Jaxon Smith-Njigba", "WR")),
    2023: (("Caleb Williams", "QB"), ("Jonathon Brooks", "RB"), ("Malik Nabers", "WR")),
    2024: (("Cam Ward", "QB"), ("Ashton Jeanty", "RB"), ("Tetairoa McMillan", "WR")),
}

DRAFTABLE_PREFIX = "ffc"
POOL_PREFIX = "ffa"


class VintageError(ValueError):
    """A season file carries a player who did not exist when it claims to have been written."""


class ScoringGapError(ValueError):
    """The league scores a stat the projection has no column for, and it was not declared."""


class PoolError(ValueError):
    """A position's projected pool is too short for replacement level to be a real baseline."""


@dataclass(frozen=True, slots=True)
class SeasonFFA:
    """One season's FFA projection, joined to the room's board and ready to be a board.

    `lines` covers every draftable row and then the tail, in a fixed order that does not depend
    on any score, so two boards built from this agree row for row and their digests compare.
    """

    season: int
    lines: tuple[Any, ...]
    # Room-board rank -> FFA's own `points_vor`, for the `ffa_vor` arm. A third party's
    # replacement transform over the same inputs, which is what splits "the idea does not work
    # here" from "our implementation of it is weaker".
    ffa_vor: dict[str, float]
    # Board key -> VORP under FFA's baseline DEPTH but OUR points and OUR rulebook. The
    # like-for-like implementation arm; see `ffa_baseline_ranks` for why the published column
    # is not one.
    ffa_baseline: dict[str, float]
    baseline_ranks: dict[str, int]
    matched: int
    unmatched: int
    pool: int
    unsupplied: tuple[str, ...]
    provenance: tuple[str, ...]

    def digest(self) -> str:
        """A stable hash of the stat lines, so G4 can assert two arms share one projection."""
        h = hashlib.sha256()
        for line in self.lines:
            h.update(line.player_id.encode())
            h.update(line.primary_position.encode())
            for key in sorted(line.stats):
                h.update(f"{key}={line.stats[key]:.6f}".encode())
        return h.hexdigest()[:16]

    def value_digest(self) -> str:
        """A hash of the EXTERNAL value columns the FFA arms order on.

        `digest()` covers the stat lines and nothing else, so it is identical for every arm
        built off one projection -- which is what makes it the right thing for G4 and the WRONG
        thing for detecting that an FFA arm's ordering changed. An adversarial review negated
        every `points_vor` and watched the digest sit still while the arm's top five turned
        over completely. This is what moves when that happens.
        """
        h = hashlib.sha256()
        for label, table in (("vor", self.ffa_vor), ("baseline", self.ffa_baseline)):
            h.update(label.encode())
            for key in sorted(table):
                h.update(f"{key}={table[key]:.6f}".encode())
        return h.hexdigest()[:16]


def _path(season: int, template: str) -> Path:
    path = FFA_DIR / template.format(season=season)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is not on disk. The FFA CSVs are gitignored and subscription-derived; "
            f"see sim/data/ffa/README.md. Nothing is substituted for a missing season."
        )
    return path


def _float(value: str | None) -> float:
    """A cell to a number. Blank and FFA's literal `NA` are zero; anything else must parse."""
    if value is None:
        return 0.0
    text = value.strip()
    if not text or text == "NA":
        return 0.0
    return float(text)


def read_raw(season: int) -> list[dict[str, str]]:
    """`raw_stats_<season>_wk0.csv`, deduplicated on `id`, first row wins.

    The duplicates are real and they are not uniform: 2019 ships 2,238 rows for 1,661 distinct
    ids including five under a placeholder `nfl_0` with no name, while 2021-2026 ship between
    4 and 12 duplicate ids each. First-row-wins is deterministic given a fixed file, which is
    what the artifact digest needs; the count of what was dropped is reported rather than
    hidden.
    """
    path = _path(season, RAW_FILE)
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    seen: set[str] = set()
    out: list[dict[str, str]] = []
    for row in rows:
        key = (row.get("id") or "").strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(row)
    return out


def read_projections(season: int) -> list[dict[str, str]]:
    """`projections_<season>_wk0.csv`. FFA's own points, `points_vor` and rank."""
    path = _path(season, PROJ_FILE)
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def columns(season: int) -> frozenset[str]:
    """The header of the season's raw-stats file."""
    path = _path(season, RAW_FILE)
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        return frozenset(next(reader))


def board_key(name: str, position: str, team: str | None) -> str:
    """The join key `room.BoardRow.key` uses: team for a defence, normalised name otherwise."""
    if position.upper() in DEF_POSITIONS:
        return f"DEF:{team}"
    return f"P:{normalize(name)}"


def assert_scoreable_season(season: int) -> None:
    """G7. 2026 has no outcome, so it cannot be an arm."""
    if season in UNPLAYED:
        raise ValueError(
            f"season {season} has not been played and cannot be scored. Loading it into an "
            f"arm is a leak of a different kind: an unresolved season scored against nothing. "
            f"Scoreable seasons are {list(SCOREABLE)}."
        )


def following_class(season: int) -> tuple[tuple[str, str], ...]:
    """The season+1 rookie class as (normalised name, position), from the next file itself.

    DERIVED, NOT REMEMBERED. The README's check was five names typed from memory; this is the
    whole class -- 54 to 178 players a year, `draft_year == season + 1` -- so the gate scales
    with the data instead of with what someone happened to recall. `draft_year` is populated
    for 92-96% of rows in every file measured, and the unpopulated tail is undrafted free
    agents, who by construction are not a draft class.

    NAME AND POSITION, because name alone produces a FALSE POSITIVE and did. Linebacker Josh
    Allen entered the league in 2019 and quarterback Josh Allen in 2018, so a name-only check
    reads the 2018 file as carrying a member of the 2019 class and rejects a genuinely vintage
    file. Pairing the position separates them, and a leak that also changed position is not a
    leak this check was ever going to catch.

    Falls back to `FOLLOWING_CLASS` when the next season's file is not on disk, so the newest
    season on disk is still checked rather than silently exempt.
    """
    try:
        rows = read_raw(season + 1)
    except FileNotFoundError:
        return tuple(
            (normalize(name), position)
            for name, position in FOLLOWING_CLASS.get(season, ())
        )
    out = {
        (normalize(row.get("player") or ""), row.get("position") or "")
        for row in rows
        if (row.get("draft_year") or "").strip() == str(season + 1)
    }
    return tuple(sorted(pair for pair in out if pair[0] and pair[0] != "na"))


def assert_vintage(season: int) -> None:
    """G5. The file must not carry the FOLLOWING year's draft class.

    Cheap, and the only thing standing between this dataset and a silent leak: a file
    regenerated by today's model would contain them and a genuine vintage file cannot.
    """
    expected = following_class(season)
    if not expected:
        raise VintageError(
            f"season {season} has no following-class check available: neither "
            f"{RAW_FILE.format(season=season + 1)} nor a FOLLOWING_CLASS entry exists. A "
            f"season is not loadable until the check exists -- an unchecked file is exactly "
            f"the one that leaks."
        )
    present = {
        (normalize(row.get("player") or ""), row.get("position") or "")
        for row in read_raw(season)
    }
    present |= {
        (normalize(row.get("player") or ""), row.get("position") or "")
        for row in read_projections(season)
    }
    leaked = sorted(
        f"{name} ({position})"
        for name, position in expected
        if (name, position) in present
    )
    if leaked:
        raise VintageError(
            f"season {season} projection carries {len(leaked)} member(s) of the {season + 1} "
            f"draft class -- {leaked[:6]}. This file is not vintage: it was regenerated after "
            f"the fact and every number built from it reads the outcome."
        )


def effective_scoring(
    config: Any, position: str, deltas: dict[str, float] | None = None
) -> dict[str, float]:
    """The weights a position is ACTUALLY scored under, deltas included.

    The deltas are the whole reason this is a function. `roundtrip.HISTORICAL_DELTAS` is
    `{"rec": 0.0}` and it is applied at the moment an OUTCOME is scored (`weekly.py`), so a
    board built from `config.scoring_for(position)` alone is ordered under a rulebook the
    outcome is not scored under. Reading the effective weights here is what keeps the two
    sides on one rulebook, and it is also what makes the reception gap a non-issue for this
    league rather than a hardcoded list of seasons.
    """
    weights = dict(config.scoring_for(position))
    if deltas:
        weights.update(deltas)
    return weights


def with_deltas(config: Any, deltas: dict[str, float] | None) -> Any:
    """The league config as the historical seasons were ACTUALLY scored.

    WHY THIS EXISTS, and it is a defect this session found rather than a convenience.
    `weekly.weekly_points` applies `HISTORICAL_DELTAS` when it scores an OUTCOME, so league
    6012's 2021-2025 receptions are paid 0.0. Nothing applies them when a BOARD is built:
    `audible/draft/board.py` scores a line with `config.scoring_for(primary)` and the
    committed TOML pays WR and TE 0.5 a catch, because that table describes 2026. So B4's
    projected and hindsight boards ordered every pass-catcher under a rulebook the outcome was
    never scored under.

    (`weekly.league_config`'s docstring says it returns the config "with the historical scoring
    deltas applied". Its body is a bare `load_league` and applies none. The deltas reach the
    outcome from the other call site; the docstring is simply wrong, and a wrong comment is a
    defect. It is named here rather than edited because that function is B4's and this session
    must not move B4's numbers underneath its committed artifact.)

    The override table is updated too, not just the base: `scoring_for` layers a position's
    overrides ON TOP of the base table, so a delta written only into the base would be silently
    reverted for any position that names the same key.
    """
    if not deltas:
        return config
    scoring = {**config.scoring, **deltas}
    by_position = {
        position: {**overrides, **{k: v for k, v in deltas.items() if k in overrides}}
        for position, overrides in (config.scoring_by_position or {}).items()
    }
    return config.model_copy(update={"scoring": scoring, "scoring_by_position": by_position})


def assert_scoreable(
    season: int, config: Any, deltas: dict[str, float] | None = None
) -> tuple[str, ...]:
    """G3. Every non-zero scoring term must be supplied or declared. Returns what was declared.

    THIS IS THE GATE THE README'S SEASON LIST WAS TRYING TO BE, and it is strictly better,
    because it reads the weights the run will actually apply. Under `espn_danger_zone`
    (1.0 a reception, no deltas) a 2021 load raises here. Under `espn_davis_drive` with the
    historical deltas the reception weight is 0.0 and the same file is fine. A hardcoded list
    of "PPR seasons" cannot express that and would have been wrong in both directions.
    """
    have = columns(season)
    supplied = {key for col, key in COLUMN_TO_KEY.items() if col in have} | SYNTHETIC_KEYS
    supplied |= {DERIVED_KEYS[key] for key in list(supplied) if key in DERIVED_KEYS}
    declared: set[str] = set()
    missing: list[tuple[str, str]] = []
    for position in sorted(config.positions):
        if position in ZERO_POSITIONS:
            continue
        for key, weight in effective_scoring(config, position, deltas).items():
            if not weight or key in supplied:
                continue
            if key in DECLARED_UNSUPPLIED:
                declared.add(key)
                continue
            missing.append((position, key))
    if missing:
        detail = ", ".join(f"{pos}:{key}" for pos, key in sorted(missing))
        raise ScoringGapError(
            f"season {season} projection has no column for scoring term(s) {detail}, and none "
            f"is declared in DECLARED_UNSUPPLIED. `score_stat_line` would resolve them with "
            f"`stats.get(key, 0.0)` and produce a board that looks entirely reasonable and is "
            f"scored under a rulebook this league does not use. Columns present: "
            f"{sorted(have)}."
        )
    return tuple(sorted(declared))


def _stats_for(row: dict[str, str], position: str, have: frozenset[str]) -> dict[str, float]:
    """One FFA row's stat line in the audible vocabulary, bucketed exactly as the board expects."""
    if position in ZERO_POSITIONS:
        return {}
    stats: dict[str, float] = {}
    for column, key in COLUMN_TO_KEY.items():
        if column in have:
            stats[key] = _float(row.get(column))
    raw = stats.pop(PASS_YARDS_RAW, 0.0)
    # `bucket25` returns YARDS TRUNCATED TO A MULTIPLE OF 25, not a count of buckets, and the
    # distinction is a factor of twenty-five. The league weight `pass_yd = 0.04` is per YARD --
    # 4,000 yards is 160 points -- so dividing by 25 and stopping scores a quarterback 6.4.
    # Written the same way `roundtrip.bucket25` writes it, from the same constant, because the
    # first draft of this line did divide and stop and it cost the QB baseline 130 points.
    stats["pass_yd"] = BUCKET * int(raw / BUCKET)
    return stats


def build(
    season: int,
    config: Any,
    *,
    deltas: dict[str, float] | None = None,
    adp_market: str | None = None,
) -> SeasonFFA:
    """One season's FFA projection as `RawPlayerLine`s over the room's own draft pool.

    THE UNIVERSE IS THE ROOM'S BOARD FIRST, THEN THE TAIL, and the order never depends on a
    score. The draftable half is keyed `ffcNNNN` by board rank because that is the key space
    `sim/boards._order_by` maps into; a line keyed anything else is a row the room cannot
    draft. The tail exists so replacement level has a real pool to find a baseline in and is
    keyed `ffa:<mfl id>`.

    A board row FFA does not project still gets a line, with an empty stat line, so it sorts
    last. It must exist: `_order_by` refuses an ordering that does not cover every draftable
    row, on the ground that two arms seeing different universes are not comparable. Measured
    coverage of the drafted top 128 is 127-128 of 128 in every season.
    """
    from audible.models.player import RawPlayerLine

    assert_scoreable_season(season)
    assert_vintage(season)
    unsupplied = assert_scoreable(season, config, deltas)

    have = columns(season)
    rows = read_raw(season)
    by_key: dict[str, dict[str, str]] = {}
    for row in rows:
        position = POSITION_MAP.get(row.get("position") or "", row.get("position") or "")
        key = board_key(row.get("player") or "", position, row.get("team"))
        by_key.setdefault(key, row)

    published = ffa_published_vor(season)

    board = room.load_board(season)
    lines: list[Any] = []
    claimed: set[str] = set()
    matched = 0
    ffa_vor: dict[str, float] = {}
    for row in board.rows:
        player_id = f"{DRAFTABLE_PREFIX}{row.rank:04d}"
        source = by_key.get(row.key)
        if source is not None:
            claimed.add((source.get("id") or "").strip())
            matched += 1
        stats = _stats_for(source, row.position, have) if source is not None else {}
        if adp_market:
            # Only the draftable half carries an ADP, so `adp_rank` is a rank over the market's
            # own list and the pool tail cannot shift it.
            stats[adp_market] = float(row.adp)
        lines.append(
            RawPlayerLine(
                player_id=player_id,
                name=row.name,
                primary_position=row.position,
                eligible_positions=frozenset({row.position}),
                team=row.team,
                stats=stats,
                ids={},
                years_exp=None,
            )
        )
        if row.key in published:
            ffa_vor[player_id] = published[row.key]

    # The tail, in a fixed order that no score touches.
    for row in sorted(rows, key=lambda r: (r.get("id") or "").strip()):
        ident = (row.get("id") or "").strip()
        if ident in claimed:
            continue
        position = POSITION_MAP.get(row.get("position") or "", row.get("position") or "")
        if position not in config.positions:
            continue
        lines.append(
            RawPlayerLine(
                player_id=f"{POOL_PREFIX}:{ident}",
                name=row.get("player") or f"ffa {ident}",
                primary_position=position,
                eligible_positions=frozenset({position}),
                team=row.get("team") or None,
                stats=_stats_for(row, position, have),
                ids={"mfl_id": ident},
                years_exp=None,
            )
        )

    ranks = ffa_baseline_ranks(season)
    ffa_baseline = _baseline_vorp(lines, config, ranks)

    return SeasonFFA(
        season=season,
        lines=tuple(lines),
        ffa_vor=ffa_vor,
        ffa_baseline=ffa_baseline,
        baseline_ranks=ranks,
        matched=matched,
        unmatched=len(board.rows) - matched,
        pool=len(lines),
        unsupplied=unsupplied,
        provenance=(
            RAW_FILE.format(season=season),
            PROJ_FILE.format(season=season),
            f"ffc_adp_standard_8_{season}",
        ),
    )


def _baseline_vorp(
    lines: list[Any], config: Any, ranks: dict[str, int]
) -> dict[str, float]:
    """OUR points minus the baseline FFA's DEPTH picks out of OUR pool, per position.

    The whole point is that only the depth crosses over. The points are the ones this league's
    rulebook produces, the pool is the one every other arm sees, and the baseline is
    `at_pos[rank]` exactly as `replacement_levels` would compute it -- including its
    fall-off-the-end rule, so a depth deeper than the pool reads 0.0 the same way and G6's
    margin still governs.
    """
    from audible.scoring.engine import score_stat_line

    scored: dict[str, list[tuple[float, str]]] = {}
    points: dict[str, float] = {}
    for line in lines:
        value = score_stat_line(line.stats, config.scoring_for(line.primary_position))
        points[line.player_id] = value
        scored.setdefault(line.primary_position, []).append((-value, line.player_id))

    baseline: dict[str, float] = {}
    for position, rows in scored.items():
        rows.sort()
        depth = ranks.get(position)
        if depth is None:
            continue
        baseline[position] = -rows[depth][0] if depth < len(rows) else 0.0

    out: dict[str, float] = {}
    for line in lines:
        if line.primary_position in baseline:
            out[line.player_id] = points[line.player_id] - baseline[line.primary_position]
    return out


def ffa_baseline_ranks(season: int) -> dict[str, int]:
    """Per position, HOW DEEP FFA sets its replacement baseline, as a rank into its own list.

    THIS IS THE ARM, AND THE PUBLISHED `points_vor` COLUMN IS NOT. An adversarial review of
    the first version of this file established that reading `points_vor` straight off the CSV
    does not measure what the arm claims to measure, and the evidence was decisive:

      * FFA's export is scored under FFA'S OWN RULEBOOK, which is not this league's. Regressing
        (FFA points - our recomputed points) on projected receptions gives slope 0.4991 in 2024
        and 0.4987 in 2025 with intercepts of +0.12 and +0.16 -- FFA is paying HALF A POINT A
        CATCH in exactly the two seasons whose files carry a `rec` column, while league 6012
        paid ZERO per reception in all five and the outcome is scored at zero.
      * So `audible_transform - <published points_vor>` was not the implementation difference.
        Holding the rulebook fixed and changing only the baseline moved it from -81.6 to -48.7
        over the same units: roughly forty per cent of that headline was the scoring table, and
        the contamination is concentrated in 2024-2025 (-125.3 there against -52.5 in
        2021-2023).

    What survives that, and what this function returns, is the DESIGN DECISION: how far down
    its own list a third party puts the baseline. Applying FFA's DEPTH to OUR points holds the
    projection, the rulebook and the pool fixed and varies only the thing the two
    implementations actually disagree about.

    Derivation: FFA publishes `points` and `points_vor` per player, and their difference is the
    baseline it subtracted, constant within a position. The mode of that difference is the
    baseline value, and the rank is how many players at the position FFA scores above it.

    THE DEPTHS ARE NOT CLOSE. FFA lands near QB12-14, TE12-14, RB35-36, WR36-38; audible's
    `rostered_counts` over the same pool gives QB9, TE18, RB53, WR36. Note also that FFA serves
    a TWELVE-team baseline and this league is eight, so part of what this arm prices is that
    difference rather than pure implementation quality. It is reported as such.
    """
    from collections import Counter

    buckets: dict[str, Counter[float]] = {}
    points: dict[str, list[float]] = {}
    for row in read_projections(season):
        position = POSITION_MAP.get(row.get("position") or "", row.get("position") or "")
        try:
            total = float(row["points"])
            vor = float(row["points_vor"])
        except (TypeError, ValueError, KeyError):
            continue
        # Rounded to a tenth: the CSV publishes both columns rounded, so the difference carries
        # a little float dust that would otherwise split one baseline into several buckets.
        buckets.setdefault(position, Counter())[round(total - vor, 1)] += 1
        points.setdefault(position, []).append(total)

    ranks: dict[str, int] = {}
    for position, counter in buckets.items():
        baseline, _count = counter.most_common(1)[0]
        ranks[position] = sum(1 for value in points[position] if value > baseline)
    return ranks


def ffa_published_vor(season: int) -> dict[str, float]:
    """Board key -> FFA's published `points_vor`, CONFOUNDED and reported as such.

    Kept because the handoff asked for FFA's own column and because dropping a measurement
    because it came out awkward is how a session becomes worth less than no session. It is not
    a like-for-like arm: see `ffa_baseline_ranks` for the rulebook contamination and its size.

    `points_vor` and not `rank`, and measurement says the choice barely matters: ordering the
    file by `rank` leaves `points_vor` non-increasing across EVERY adjacent pair in all five
    seasons, so `rank` is a pure `points_vor` sort and the two disagree only on how ties are
    broken. (Against a sort on raw `points` it agrees on 0 to 4 rows of 477-495: FFA's
    published rank is a replacement-level rank and not a points rank.)
    """
    out: dict[str, float] = {}
    for row in read_projections(season):
        position = POSITION_MAP.get(row.get("position") or "", row.get("position") or "")
        key = board_key(row.get("player") or "", position, row.get("team"))
        value = row.get("points_vor")
        if value is None or not str(value).strip() or str(value).strip() == "NA":
            continue
        out.setdefault(key, float(value))
    return out


def pool_margin(
    season: int, config: Any, deltas: dict[str, float] | None = None
) -> dict[str, dict[str, int]]:
    """G6. Per position: how many the projection carries against how many get rostered.

    Replacement level is `at_pos[taken].points if taken < len(at_pos) else 0.0`
    (`audible/value/replacement.py:168`). A pool shorter than the rostered count therefore does
    not fail -- it reads 0.0, hands every player at that position his FULL projection as VORP,
    and inflates precisely the arm whose entire mechanism is replacement level. A prior review
    found exactly this with 18 tight ends against 18 rostered, which put Brock Bowers first
    overall. So the margin is asserted per position and reported for every season.
    """
    from audible.value.replacement import assign_starters, rostered_counts

    season_ffa = build(season, config, deltas=deltas)
    projections = [_projection(line, config, deltas) for line in season_ffa.lines]
    starters = assign_starters(projections, config)
    taken = rostered_counts(projections, config, starters)

    out: dict[str, dict[str, int]] = {}
    for position in sorted(config.positions):
        have = sum(1 for p in projections if p.primary_position == position)
        out[position] = {
            "pool": have,
            "rostered": taken[position],
            "margin": have - taken[position],
        }
    return out


def assert_pool(
    season: int, config: Any, deltas: dict[str, float] | None = None, *, floor: int = 1
) -> dict[str, dict[str, int]]:
    """G6, enforced. A margin at or below *floor* raises rather than reading 0.0."""
    margins = pool_margin(season, config, deltas)
    thin = {p: m for p, m in margins.items() if p not in ZERO_POSITIONS and m["margin"] < floor}
    if thin:
        detail = ", ".join(
            f"{p}: {m['pool']} projected vs {m['rostered']} rostered"
            for p, m in sorted(thin.items())
        )
        raise PoolError(
            f"season {season} pool is too short at {detail}. Replacement level would fall off "
            f"the end of the list and read 0.0, handing every player at that position his full "
            f"projection as VORP and inflating the one arm whose mechanism is replacement level."
        )
    return margins


def _projection(line: Any, config: Any, deltas: dict[str, float] | None) -> Any:
    from audible.models.player import PlayerProjection
    from audible.scoring.engine import score_stat_line

    weights = effective_scoring(config, line.primary_position, deltas)
    return PlayerProjection(
        player_id=line.player_id,
        name=line.name,
        primary_position=line.primary_position,
        eligible_positions=line.eligible_positions,
        team=line.team,
        points=score_stat_line(line.stats, weights),
    )


def manifest() -> dict[str, dict[str, Any]]:
    """sha256, row count and column set per file on disk.

    The CSVs are never committed, so this is how a run asserts it read the same bytes the
    artifact claims. Regenerate whenever a season is added.
    """
    out: dict[str, dict[str, Any]] = {}
    for path in sorted(FFA_DIR.glob("*.csv")):
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        with path.open(encoding="utf-8", newline="") as handle:
            reader = csv.reader(handle)
            header = next(reader)
            rows = sum(1 for _ in reader)
        out[path.name] = {"sha256": digest, "rows": rows, "columns": header}
    return out
